### ISSUE TITLE
Support for newer intellij

### ISSUE THREAD

**Issue by MattiDragon** [roscopeco/jasm-intellij-plugin#1]
This doesn't currently support the latest intellij version

**Comment by roscopeco** [comment]
Thanks for pointing this out, I will get this fixed as soon as possible 👍

**Comment by roscopeco** [comment]
I have just submitted plugin version 0.6.1 to Jetbrains review process. This version will work on IntelliJ builds up to the current stable 2022.1.3 (221) version.

Thanks again for the report!
